In [3]:
# importowanie potrzebnych modułów
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [6]:
from math import exp

### Implementacja algorytmu genetycznego

1. Inicjalizacja:

In [787]:
# prawdopodobieństwo selekcji:
#selectionProbability = 0.7
# prawdopodobieństwo mutacji:
mutationPr = 0.01
# dodatkowo prawdopodobieństwo mutacji można potraktować tak jak parametr temperatury w wyżarzaniu symulowanym 
# - zmniejszać go w czasie - -exp(liczbaIteracji)
for i in range(10):
    print(mutationPr/np.exp(i/10))



0.01
0.00904837418036
0.00818730753078
0.00740818220682
0.00670320046036
0.00606530659713
0.00548811636094
0.00496585303791
0.00449328964117
0.00406569659741


In [4]:
np.random.seed(42)

In [28]:
# randomowe liczby, od 0 do 1, fitness function to log
fitnessValue = np.zeros(100)
for i in range(1, 100):
    fitnessValue[i-1] = np.log(np.random.random()+1)

In [29]:
fitnessValue[:5]

array([ 0.68594655,  0.21676748,  0.51410158,  0.56623362,  0.21320436])

In [97]:
# liczba chromosomów w populacji
n_pop = 10
# liczba genów per chromosom
n_ch = 2
init_weights = np.random.random((n_pop, n_ch))
#init_weights = np.dot(0.5, np.ones((n_pop, n_ch)))
init_weights

array([[ 0.68423303,  0.44015249],
       [ 0.12203823,  0.49517691],
       [ 0.03438852,  0.9093204 ],
       [ 0.25877998,  0.66252228],
       [ 0.31171108,  0.52006802],
       [ 0.54671028,  0.18485446],
       [ 0.96958463,  0.77513282],
       [ 0.93949894,  0.89482735],
       [ 0.59789998,  0.92187424],
       [ 0.0884925 ,  0.19598286]])

In [89]:
np.ones((10, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [16]:
def funkcja_aktywacji(x):
    return 1/(1+exp(-x))

koszt wysyłki - 0.1 per recipient
zysk - 20 per positive response

In [107]:
1772*20

35440

In [105]:
226000*0.1

22600.0

In [143]:
# macierz kosztu = [TP, FP, TN, FN]
def funkcjaKosztu(k):
    # funkcja przyjmuje jako argument macierz 2x2
    cost_matrix = np.array([-19.9, 0.1, 0, 20.1])
    return np.round(np.dot(k, cost_matrix), 5)

In [110]:
# MLP
funkcjaKosztu([338, 9940, 46182, 108])

-3561.3999999999996

In [111]:
# log
funkcjaKosztu([331, 6213, 49909, 115])

-3654.0999999999995

In [99]:
weights = init_weights[0]
weights

array([ 0.68423303,  0.44015249])

In [131]:
input_matrix = np.array([[1, 1, 0, 0], [1, 0, 1, 0]])
output_matrix = [np.dot(w, input_matrix[i]) for i, w in enumerate(weights)]  
expected_output = np.array([1, 0, 0, 0])

In [101]:
output_matrix

[array([ 0.68423303,  0.68423303,  0.        ,  0.        ]),
 array([ 0.44015249,  0.        ,  0.44015249,  0.        ])]

In [145]:
np.sum(output_matrix, axis=0)

array([ 1.12438552,  0.68423303,  0.44015249,  0.        ])

In [146]:
hat_matrix

array([ 0.75480128,  0.66468281,  0.60829537,  0.5       ])

In [136]:
hat_matrix = np.sum(output_matrix, axis=0)
pred_matrix = np.zeros(len(expected_output), dtype=int)
for i, h in enumerate(hat_matrix):
    hat_matrix[i] = funkcja_aktywacji(hat_matrix[i])
    if hat_matrix[i] > 0.5:
        pred_matrix[i] = 1
    else:
        pred_matrix[i] = 0

In [120]:
np.sum(pred_matrix - expected_output)

2.0

In [137]:
pred_matrix

array([1, 1, 1, 0])

In [132]:
expected_output

array([1, 0, 0, 0])

In [103]:
hat_matrix

array([ 0.75480128,  0.66468281,  0.60829537,  0.5       ])

In [139]:
def macierzKontyngencji(wektor_predykcji, wektor_rzeczywisty):
    mK = np.zeros(4)
    for i in range(len(wektor_predykcji)):
        if (wektor_rzeczywisty[i] == 1) & (wektor_predykcji[i] == 1):
            mK[0] += 1
        elif (wektor_rzeczywisty[i] == 0) & (wektor_predykcji[i] == 1):
            mK[1] += 1
        elif (wektor_rzeczywisty[i] == 0) & (wektor_predykcji[i] == 0):
            mK[2] += 1
        elif (wektor_rzeczywisty[i] == 1) & (wektor_predykcji[i] == 0):
            mK[3] += 1
    return mK

In [141]:
mk = macierzKontyngencji(pred_matrix, expected_output)

In [194]:
funkcjaPrzystosowania = -funkcjaKosztu(mk)
funkcjaPrzystosowania

19.699999999999999

Test Data Set

In [147]:
from sklearn.datasets import load_iris

In [190]:
c1 = np.array(load_iris().data)
c2 = np.array(load_iris().target)
df = pd.DataFrame(c1, columns=load_iris().feature_names)
df['target'] = np.array(c2)

In [193]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [197]:
df.shape[0]

150

Przykladowa siec:

In [209]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
%matplotlib inline
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report


In [269]:
dataset = df[df['target']!=2]

In [271]:
X = dataset.drop(labels= ['target'], axis = 1)

In [272]:
Y = dataset['target']

In [273]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

In [274]:
X_train_sc = StandardScaler().fit(X_train).transform(X_train)
X_test_sc = StandardScaler().fit(X_test).transform(X_test)

In [522]:
np.random.seed = 42

In [405]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100), early_stopping=False, random_state=2)
mlp.fit(X_train_sc, Y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=2, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [570]:
?mlp

In [589]:
siec(chromosom)

array([[17,  0],
       [ 0,  8]], dtype=int64)

In [406]:
predict = mlp.predict(X_test_sc)

In [407]:
print(confusion_matrix(Y_test, predict))

[[17  0]
 [ 0  8]]


In [401]:
print(classification_report(Y_test, predict))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        17
          1       1.00      1.00      1.00         8

avg / total       1.00      1.00      1.00        25



__Implementacja__

Struktura:


Potrzebne funkcje:
- selekcja - metoda ruletki
- mutacja - zmniejszajacy sie wspołczynnik mutacji
- krzyżowanie - single-point crossover
- funkcja przystosowania - 

Optymalizowane parametry:
 - ilość warstw ukrytych
 - liczba neuronów w warstwach ukrytych
 - funkcja aktywacji (1, 2, 3)
 - learning rate (constant, invscaling - 0, 1)
 - learning rate init (1000 - 1)
Kodowanie architektury:
 - chromosom - pojedynczy ciąg znaków, gdzie pierwsze trzy

In [205]:
#chromosome 
ch = [1, 0, 3, 3, 3, 3, 0, 0, 0, 0]
pop = np.zeros((3, 6))

In [206]:
pop

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [872]:
def selekcja(populacja, przystosowanie):
    '''
    Funkcja selekcji - wybierająca chromosomy do krzyżowania
    
    Parametry:
    - populacja (dict) - słownik z aktualną populacją
    - przystosowanie (dict) - słownik z wartościami funkcji przystosowania dla każdego chromosomu w populacji
    
    Zwraca:
    - nowa_populacja (dict) - słownik z nową populacją
    
    '''
    fitness = przystosowanie
    mmsc = MinMaxScaler(feature_range=(0,100)).fit_transform(fitness.reshape(-1, 1))
    s = sum(mmsc)
    mmsc = mmsc/s*100
    f_total = []
    for m, i in enumerate(mmsc):
        for j in range(int(i)):
            f_total.append(m)
    parents_pool = np.copy(f_total)
    for j in range(len(populacja)):
        # wybieranie losowych rodziców metodą ruletki
        father = np.random.choice(parents_pool)
        # drugi rodzic nie może być taki sam jak pierwszy
        mother = parents_pool[parents_pool!=father]
        # jeśli pozostał tylko jeden rodzic w populacji to muszę go wybrać
        if len(mother) == 0:
            mother = father
        else:
            mother = np.random.choice(mother)
        father = populacja[father]
        mother = populacja[mother]
        c = np.random.randint(1, len(father))
        child = np.concatenate([father[:c], mother[c:]])
        # mutacja
        mutationPr = 0.25
        wsp_mutacji = mutationPr/np.exp(i/10) 
        m = np.random.random()
        if m < wsp_mutacji:
            child = mutacja(child)
        nowa_populacja[j] = child
    
    return nowa_populacja
    

In [864]:
def mutacja(chromosom):
    '''
    
    Funkcja mutacji - zmieniajaca losowo jeden z parametrow chromosomu
    Wybiera losowy gen i zastepuje jego wartość dowolną wartość dozwoloną dla tego genu
    
    Parametry:
    - chromosom (list) - wektor reprezentujacy chromosom
    
    Zwraca:
    - m_chromosom (list) - zmutowany chromosom
    
    '''
    
    # parametr który ma zostać zmutowany
    p = np.random.randint(0, len(chromosom))
    m_chromosom = chromosom.copy()
    pT = parametryTopologii()[p]
    pT.pop(pT.index(m_chromosom[p]))
    m_chromosom[p] = np.random.choice(pT)
    return m_chromosom
    

In [595]:
def parametryTopologii():
    '''
    
    '''
    
    fa = [1, 2, 3] #funkcja aktywacji
    lt = [0, 1] # współczynnik uczenia
    lr = list(range(1, 1001, 1)) # startowy współczynnik uczenia
    hl = list(range(1, 6)) # liczba warstw ukrytych
    nn = list(range(1, 129)) # liczba neuronów w warstwie
    parametry = {0:fa, 1:lt, 2:lr, 3:hl, 4:nn}

    return parametry

In [623]:
def siec(chromosom):
    '''
    
    Funkcja tworząca nową sieć na podstawie otrzymanego chromosomu
    Parametry:
     - chromosom
     
    Zwraca:
     - macierz - macierz kontyngencji 
    
    '''
    f_aktywacji = {1:'logistic', 2:'tanh', 3:'relu'}
    wsp_uczenia = {0:'constant', 1:'invscaling'}
    warstwy = tuple(np.ones(chromosom[3], dtype=int)*chromosom[4])
    mlp = MLPClassifier(hidden_layer_sizes=warstwy, activation=f_aktywacji[chromosom[0]],\
                        learning_rate=wsp_uczenia[chromosom[1]], learning_rate_init = 1/(2*chromosom[2]))
    
    mlp.fit(X_train_sc, Y_train)
    prognoza = mlp.predict(X_test_sc)
    macierz = confusion_matrix(Y_test, prognoza)
    return macierz
    
    

In [528]:
chromosom = [2, 1, 2, 3, 4]
chromosom[0] = np.random.choice(parametryTopologii()[0])


In [642]:
# macierz kosztu = [TP, FP, TN, FN]
def funkcjaZysku(k):
    '''
    Funkcja obliczajaca wartosci zysku danej sieci na podstawie macierzy kontyngencji składającej się z:
    TruePositive, FalsePositive, TrueNegative, FalseNegative
    
    Parametry:
    k (list) - lista zawierajaca liczbe wartosci każdej z czterech możliwych kombinacji klasyfikacji 
    
    Zwraca:
    koszt (float) - liczba rzeczywista określająca zysk związany z danym efektem klasyfikacji
    
    '''
    
    cost_matrix = np.array([19.9, -0.1, 0, -20.1])
    zysk = np.round(np.dot(k, cost_matrix), 5) 
    return zysk

In [845]:
def startowaPopulacja(liczebnosc_pop):
    '''
    Funkcja tworząca startową populacje
    
    Zwraca:
    populacja (dict) - słownik z listami chromosomow
    
    '''
    populacja = {}
    #liczebnosc_pop = 10

    for j in range(liczebnosc_pop):
        ch2 = np.ones(5, dtype=int)
        for i in range(5):
            ch2[i] = np.random.choice(parametryTopologii()[i])
        populacja[j] = ch2
    return populacja

In [628]:
populacja[1]

array([  3,   1, 179,   1,  85])

In [873]:
epochs = 10
liczebnosc_pop = 10
f_fit = {}
average_fitness = np.zeros(liczebnosc_pop)
maximum_fitness = np.zeros(liczebnosc_pop)
minimum_fitness = np.zeros(liczebnosc_pop)
zb_pop = {}
populacja = startowaPopulacja(liczebnosc_pop)
for i in range(epochs):
    zb_pop[i] = populacja
    f_fit[i] = np.zeros(liczebnosc_pop)
    fitness = np.zeros(len(populacja))
    for p in range(len(populacja)):
        y = siec(populacja[p])
        # wektor w przechowuje liczby: TP, FP, TN, FN
        w = np.array([y[0][0], y[0][1], y[1][1], y[1][0]])
        fitness[p] = funkcjaZysku(w)
    f_fit[i] = fitness
    average_fitness[i] = np.mean(fitness)
    maximum_fitness[i] = np.max(fitness)
    minimum_fitness[i] = np.min(fitness)
    if minimum_fitness[i] == maximum_fitness[i]:
        print('Najmniejsza i największa wartość funkcji przystosowania są takie same.')
        print('Osiągnięto minimum lokalne.')
        print('Iteracja nr {}'.format(i+1))
        break
    nowa_populacja = selekcja(populacja, fitness)
    populacja = nowa_populacja

C:\Apps\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Najmniejsza i największa wartość funkcji przystosowania są takie same.
Osiągnięto minimum lokalne.
Iteracja nr 2


In [874]:
zb_pop

{0: {0: array([  2,   0, 237,   4,  21]),
  1: array([  3,   0, 950,   5, 125]),
  2: array([  1,   1, 826,   4, 108]),
  3: array([  2,   0, 480,   3, 100]),
  4: array([  1,   0, 282,   1,  48]),
  5: array([ 2,  0,  8,  3, 38]),
  6: array([  3,   1, 993,   3,  18]),
  7: array([  1,   1, 244,   4,  15]),
  8: array([  2,   1, 884,   5,  69]),
  9: array([  1,   1, 285,   1,  31])},
 1: {0: array([  2,   0, 480,   3,  18]),
  1: array([  2,   1, 884,   5,  31]),
  2: array([  2,   1, 285,   1,  31]),
  3: array([  1,   1, 285,   1,  48]),
  4: array([  1,   0, 282,   1,  31]),
  5: array([  3,   1, 285,   1,  31]),
  6: array([  2,   1, 884,   5,  48]),
  7: array([  2,   0, 237,   5,  69]),
  8: array([  2,   0, 480,   3,  69]),
  9: array([  2,   1, 884,   5, 100])}}

In [869]:
f_fit

{0: array([ 338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  318.3,  338.3,
          -1.7,  338.3]),
 1: array([ 338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,
          -1.7,  278.3]),
 2: array([ 338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,
         338.3,  338.3])}

In [850]:
yy = MinMaxScaler(feature_range=(0,100)).fit_transform(fitness.reshape(-1, 1))
yy

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [854]:
average_fitness

array([ 254.22,  270.3 ,  338.3 ,    0.  ,    0.  ,    0.  ,    0.  ,
          0.  ,    0.  ,    0.  ])

In [770]:
fitness = np.zeros(10)
for p in range(len(populacja)):
    y = siec(populacja[p])
    # wektor w przechowuje liczby: TP, FP, TN, FN
    w = np.array([y[0][0], y[0][1], y[1][1], y[1][0]])
    fitness[p] = funkcjaZysku(w)


C:\Apps\Anaconda\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [771]:
fitness

array([ 338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,  338.3,
        338.3,   -1.7])

In [645]:
from sklearn.preprocessing import MinMaxScaler

In [772]:
mmsc = MinMaxScaler(feature_range=(0,100)).fit_transform(fitness.reshape(-1, 1))
s = sum(mmsc)
mmsc = mmsc/s*100

In [773]:
mmsc

array([[ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [ 11.11111111],
       [  0.        ]])

In [774]:
f_total = []
for m, i in enumerate(mmsc):
    for j in range(int(i)):
        f_total.append(m)
    


In [777]:
populacja

{0: array([  1,   1, 373,   2,  73]),
 1: array([  3,   1, 179,   1,  85]),
 2: array([  2,   0, 421,   1,  49]),
 3: array([  3,   1, 398,   4,  32]),
 4: array([  3,   0, 673,   2,  43]),
 5: array([  3,   1,  78,   4, 108]),
 6: array([  3,   0, 853,   2,  91]),
 7: array([  2,   1, 228,   1,  42]),
 8: array([  2,   1, 154,   4,   2]),
 9: array([  1,   1, 557,   5,  26])}

In [778]:
mother

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [780]:
parents_pool = np.copy(f_total)
for j in range(len(populacja)):
    father = np.random.choice(parents_pool)
    mother = parents_pool[parents_pool!=father]
    if len(mother) == 0:
        mother = father
    father = populacja[father]
    mother = populacja[np.random.choice(mother)]
    c = np.random.randint(1, len(father))
    child = np.concatenate([father[:c], mother[c:]])
    # mutacja
    mutationPr = 0.25
    wsp_mutacji = mutationPr/np.exp(i/10) 
    m = np.random.random(0,1)
    if m < wsp_mutacji:
        child = mutacja(child)
    populacja[j] = child
    

In [783]:
c, father, mother, child

(2,
 array([  3,   0, 673,   2,  43]),
 array([  3,   1,  78,   4, 108]),
 array([  3,   0,  78,   4, 108]))

In [749]:
if len(mother) ==0:
    mother = father

In [746]:
type(parents_pool[parents_pool!=father])

numpy.ndarray

In [832]:
chromosom

[1, 0, 889, 5, 105]

In [843]:
for i in range(10):
    mutationPr = 0.25
    wsp_mutacji = mutationPr/np.exp(i/10) 
    m = np.random.random()
    if m < wsp_mutacji:
        print(mutacja(chromosom))
    print(wsp_mutacji, m)
    

0.25 0.4758162666307404
0.226209354509 0.47501648643083183
0.204682688269 0.8135832994005334
0.18520455517 0.9016372414070409
[1, 0, 889, 5, 14]
0.167580011509 0.0007453193212491049
0.151632664928 0.9940323672675025
0.137202909024 0.17545669581415646
0.124146325948 0.6385206275164025
0.112332241029 0.671085696280046
[1, 1, 889, 5, 105]
0.101642414935 0.06785878837279724


In [809]:
wsp_mutacji, m

(0.020328482987029956, 0.5698840941117482)

In [862]:
p = 3
m_chromosom = chromosom.copy()
pT = parametryTopologii()[p]
pT.pop(pT.index(m_chromosom[p]))
pT

[1, 2, 3, 4]

In [859]:
p

9

In [755]:
father, mother

(array([  1,   1, 557,   5,  26]), array([  1,   1, 557,   5,  26]))

In [715]:
tut = np.array([0, 0, 0, 1, 1, 2])

In [717]:
tut[tut!=0]

array([1, 1, 2])

In [608]:
mk = siec(populacja[0])
TP = mk[0][0]
TN = mk[1][1]
FP = mk[0][1]
FN = mk[1][0]

In [618]:
cost_matrix = np.array([-19.9, 0.1, 0, 20.1])

a = np.array([TP, FP, TN, FN])

In [620]:
np.round(np.dot(a, cost_matrix),3)

-338.30000000000001

In [539]:
mutacja(chromosom)

[3, 0, 90, 4, 52]

In [501]:

np.random.choice(chromosom)

2