### Notes for course

What is neural network?
- simplest neural network - linear regression
    - rectified linear unit (relu)
- takes one or more features, applies function, returns output
- Neural Networks (standard)
- Convolutional Neural Networks
- Recurrent Neural Networks
- Hybrid or Custom


Supervised learning with Neural Networks:
- input (x) -> output (y)
- applications:
    - real estate - NN
    - online advertising - NN
    - photo tagging - CNN
    - speech recognition - RNN
    - machine translation - RNN
    - automotive industry, autonomous driving - Hybrid/Custom

Structured Data vs Unstructured Data

Why is Deep Learning taking off?
- scale - more data means better model's performance
- the more data you have the bigger should network be

(m) - size of dataset

Recently we have seen 3 advances:
- more data 
- better computational power
- better algorithms - sigmoid function is slower than ReLU due to gradient being close to zero and moving forward slowly for sigmoid

Implementing Cycle:
- Idea
- Code
- Experiment  

Faster computation has sped up receiving feedback of experiments

Binary Classification:
- creating feature vector for image
- (n) - dimension of input feature vector
- (x, y) - x is R^n feature vector, y is 0 or 1
- matrix M
- vector X - m x n
- in python X.shape = (n, m)
- vector Y - 1 x m
- in python Y.shape = (1, m)


Logistic Regression:
- given input vector x produce y_hat that returns probability that given input vector is classified as 1 
- w is weight vector, b is random numbers
- y_hat should be between 0 and 1
- y_hat is equal to sigmoid function applied to w^tx + b   /(z)
- sigmoid = 1/1+e^(-z)
- if z is large, sigmoid is going to 1, if it is small or negative sigmoid goes to 0



Logistic Regression - cost function:
- Loss (error) function:
    - L(y^, y) = -(ylogy^ + (1-y)log(1-y^))
- Cost function:
    - J(w,b) = 1/m sum from i to m for L(y^(i), y(i))
- Loss function is applied to single observation
- Cost function is applied to vector of parameters and b parameter


Gradient Descent:
- find w, b minimizing J(w,b)  
- repeat derivative: dJ(w)/dw

Cost function is used to have a convex function that will enable gradient descent to minimize it  

alfa parameter - learning rate - constant


Computation Graph:
- chain rule - product of derivatives
- 

Logistic Regression Gradient Descent

Gradient Descent on m Examples

Vectorization

In [3]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
import time

a = np.random.rand(1000)
b = np.random.rand(1000)

tic = time.time()

c= np.dot(a, b)
toc = time.time()

print("Vectorized version:" + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000):
    c+= a[i] * b[i]
toc = time.time()

print ("For loop:" + str(1000*(toc - tic)) + "ms")

Vectorized version:0.06103515625ms
For loop:0.4425048828125ms


Vectorizing Logistic Regression

In [4]:
# dataset size
m = 10
# learning rate
alfa = 0.02

In [21]:
w = np.random.randn(5, 1)
b = np.random.random()

In [24]:
X = np.random.randn(5,1)

In [25]:
Z = np.dot(w.T, X) + b

In [38]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))

In [28]:
A = sigmoid(Z)

In [30]:
Y = np.random.randn(1, 5)

In [31]:
dz = A - Y

In [32]:
dz

array([[ 0.27474965, -0.04021575,  0.26028093,  0.36767797,  0.6377069 ]])

In [ ]:
dw = 1/m * X * dz
db = 1/m * np.sum(dz)

In [ ]:
w = w - alfa*dw
b = b - alfa*db

Broadcasting

Broadcasting is turning lower dimensional vector, number into higher dimensional matrix to match higher dimensional part of equation in order to perform element-wise operation

In [9]:
A = np.array([[56, 1.2, 1.8], [0.0, 104, 135], 
              [4.4, 52, 99], [68, 8, 0.9]]).T
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [11]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [13]:
percentage = np.round(100*A/cal.reshape(1,4),1)
print(percentage)

[[94.9  0.   2.8 88.4]
 [ 2.  43.5 33.5 10.4]
 [ 3.1 56.5 63.7  1.2]]


Note on python/numpy vectors

In [14]:
# rank 1 array
a = np.random.randn(5)

In [16]:
print(a.shape)

(5,)


In [18]:
a = np.random.randn(1, 5)
print(a.shape)

(1, 5)


In [33]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a*b

In [35]:
a

array([[-0.4754325 ,  0.09229966,  0.51109435],
       [-0.84397007,  1.55916485,  1.22652647],
       [-2.01315742, -1.01683205,  0.1550477 ]])

In [36]:
b

array([[-0.80622926],
       [-0.20906048],
       [-0.38928091]])

In [37]:
c

array([[ 0.38330759, -0.07441469, -0.41205922],
       [ 0.17644079, -0.32595976, -0.25641822],
       [ 0.78368376,  0.39583331, -0.06035711]])

Neural Network Representation

In [3]:
import numpy as np
# number of input features in dataset X
n = 3
# number of training examples
m = 10
X = np.random.randn(n, m)

In [4]:
X

array([[-1.1943709 ,  0.64804163,  1.46287113, -0.52703811, -0.61090275,
        -0.50749665, -1.52642989, -0.43280595,  0.89773854, -0.77337107],
       [-1.79411923, -2.38650283,  0.55769246,  0.42319424, -0.17346188,
        -1.67947422,  1.68112723, -0.3718169 ,  0.34792506, -0.04487569],
       [-1.00292944, -1.62679039,  0.07601192, -0.15329917, -1.93057677,
         0.7077116 ,  0.93751814, -2.1130156 , -0.62818298, -0.50605365]])

Activation functions:
- sigmoid used only for binary classification
- tanh is superior to sigmoid
- relu is default choice for hidden layers  

Using linear activation is almost useless and very rare - it produces linear output yhat from input set

Derivatives of activation functions:


In [1]:
# d_sigmoid = sigmoid * ( 1- sigmoid)

In [2]:
# d_tanh = 1 - (tanh**2)

In [3]:
# relu = 0 if z < 0 else 1 if z > 0 

Gradient Descent for Neural Network:

In [7]:
import numpy as np
# Initialize parameters randomly
np.random.seed(42)

In [8]:
# powtorzyc, zaimplementowac jutro